// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/uploads/*",
    "/icons/*",
    "/media/*",
    "/robots.txt"
  ]
};

// node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "/Users/jeremy/source/apps/monierate/monierate-website/.wrangler/tmp/pages-l08cS4/bundledWorker-0.5549547836939044.mjs";
import { isRoutingRuleMatch } from "/Users/jeremy/source/apps/monierate/monierate-website/node_modules/wrangler/templates/pages-dev-util.ts";
export * from "/Users/jeremy/source/apps/monierate/monierate-website/.wrangler/tmp/pages-l08cS4/bundledWorker-0.5549547836939044.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        const workerAsHandler = worker;
        if (workerAsHandler.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return workerAsHandler.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=ijt3omr46ce.js.map
